spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/kotlin-jpa
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    open-in-view: false